// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7r-9cYlvz352rysi1O2jd6Iy8r8cY2og',
    appId: '1:115099213904:web:3bfee13496098f4a0e7155',
    messagingSenderId: '115099213904',
    projectId: 'test-case-f8c02',
    authDomain: 'test-case-f8c02.firebaseapp.com',
    storageBucket: 'test-case-f8c02.firebasestorage.app',
    measurementId: 'G-Z9QMZNTYKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbR79PAPON9QVWiqm0686zRsqpjHp9GDo',
    appId: '1:115099213904:android:4cd06356cdb011790e7155',
    messagingSenderId: '115099213904',
    projectId: 'test-case-f8c02',
    storageBucket: 'test-case-f8c02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-nwVssfDAYh02g8GlnrstBqJ7EcjNZc',
    appId: '1:115099213904:ios:2157846c0f2eeab60e7155',
    messagingSenderId: '115099213904',
    projectId: 'test-case-f8c02',
    storageBucket: 'test-case-f8c02.firebasestorage.app',
    iosBundleId: 'com.example.testCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-nwVssfDAYh02g8GlnrstBqJ7EcjNZc',
    appId: '1:115099213904:ios:2157846c0f2eeab60e7155',
    messagingSenderId: '115099213904',
    projectId: 'test-case-f8c02',
    storageBucket: 'test-case-f8c02.firebasestorage.app',
    iosBundleId: 'com.example.testCase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7r-9cYlvz352rysi1O2jd6Iy8r8cY2og',
    appId: '1:115099213904:web:e3d5226d3f54bd9a0e7155',
    messagingSenderId: '115099213904',
    projectId: 'test-case-f8c02',
    authDomain: 'test-case-f8c02.firebaseapp.com',
    storageBucket: 'test-case-f8c02.firebasestorage.app',
    measurementId: 'G-654GSVK597',
  );
}
